#!/bin/sh

URL=https://svn.omniti.com/people/wez/php/JLexPHP
wd=/tmp/dist.$$

old=`pwd`

mkdir $wd
cd $wd || exit 1

v=`svn info $URL | awk '/^Revision:/ { print $2 }'`

svn export $URL JLexPHP-$v
tar cvzf JLexPHP-$v.tgz JLexPHP-$v

cp JLexPHP-$v.tgz $old
cd $old
rm -rf $wd

